name: Build Docker Image

on:
  push:
    tags:
      - 'v*' # e.g. v0.1.0
  workflow_dispatch:
    inputs:
      custom_tag:
        description: 'Custom Docker image tag (e.g., v0.1.0)'
        required: true
      push_latest:
        description: 'Also tag as latest'
        required: false
        default: false
        type: boolean

env:
  REGISTRY: ghcr.io
  # Will publish to ghcr.io/<owner>/<repo>:<tag>
  IMAGE_NAME: ${{ github.repository }}
  PLATFORM: linux/amd64

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # required for GHCR push

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute tags
        id: meta
        shell: bash
        run: |
          SHA_SHORT=$(echo "${GITHUB_SHA}" | cut -c1-7)

          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ inputs.custom_tag }}"
            TAGS="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}"
            if [[ "${{ inputs.push_latest }}" == "true" ]]; then
              TAGS="${TAGS},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
            fi
            echo "Manual build -> ${VERSION}"
          elif [[ "${{ github.ref_type }}" == "tag" ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
            TAGS="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
            echo "Tag build -> ${VERSION}"
          else
            VERSION="dev-${SHA_SHORT}"
            TAGS="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}"
            echo "Branch build -> ${VERSION}"
          fi

          echo "tags=${TAGS}" >> "$GITHUB_OUTPUT"
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
          echo "Computed tags: ${TAGS}"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.PLATFORM }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.ref.name=${{ github.ref }}
            org.opencontainers.image.title=Fluent Faucet Discord Bot
            org.opencontainers.image.version=${{ steps.meta.outputs.version }}

      - name: Summary
        shell: bash
        run: |
          echo "### Docker Image Published 🚀" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** \`${{ steps.meta.outputs.version }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Tags:**" >> $GITHUB_STEP_SUMMARY
          IFS=',' read -ra T <<< "${{ steps.meta.outputs.tags }}"
          for tag in "${T[@]}"; do
            echo "- \`${tag}\`" >> $GITHUB_STEP_SUMMARY
          done
